version: '2'
services:
  sveltekit:
    image: ghcr.io/aam-git/docker-sveltekit
    restart: unless-stopped
    volumes:
      - sveltekit_data:/usr/src/app
    networks:
      - internal
    ports:
      - 3000
volumes:
  sveltekit_data:
    driver: local